<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive Calendar - August 2024</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: teal;
            color: white;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            position: relative;
        }

        .project-title {
            font-size: 48px;
            margin-bottom: 20px;
            text-align: center;
        }

        .calendar {
            width: 80%; /* Adjusted width */
            height: 90%;
            background: white;
            color: black;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            display: flex;
            flex-direction: column;
            position: relative;
            margin-right: 150px; /* Added margin to ensure the logo isn't covered */
        }

        .calendar-title {
            text-align: center;
            font-size: 36px;
            padding: 20px 0;
            background-color: #50C878; /* Emerald Green */
            color: white;
            border-radius: 5px 5px 0 0;
            flex: 0 0 auto;
        }

        .calendar table {
            width: 100%;
            height: 100%;
            border-collapse: collapse;
            flex: 1 1 auto;
        }

        .calendar th, .calendar td {
            width: 14.28%;
            border: 1px solid #ddd;
            text-align: left;
            padding: 10px;
            cursor: pointer;
            box-sizing: border-box;
            position: relative;
            vertical-align: top;
        }

        .calendar th {
            background-color: #50C878; /* Emerald Green */
            color: white;
        }

        .calendar td .day-number {
            position: absolute;
            top: 5px;
            right: 10px;
            font-weight: bold;
            font-size: 14px;
        }

        .calendar td:hover {
            background-color: #f0f0f0;
        }

        /* Logo styles */
        .logo {
            position: absolute;
            top: 10px;
            right: 10px;
            width: 180px; /* Increased width by 50% */
            height: auto;
        }

        /* Modal styles */
        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0.5);
            padding-top: 60px;
        }

        .modal-content {
            background-color: white;
            margin: 5% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
            max-width: 600px;
            border-radius: 4px;
        }

        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover, .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }

        .modal-textarea {
            width: 100%;
            height: 150px;
            margin-top: 20px;
            font-size: 16px;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        .save-btn {
            background-color: #50C878;
            color: white;
            padding: 10px 20px;
            margin-top: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .save-btn:hover {
            background-color: #45b76b;
        }
    </style>
</head>
<body>

<div class="project-title">West Toe Scrim Project</div>

<img src="https://res.cloudinary.com/cloudasset/image/upload/v1506383811/SaceivRFHXzyUYdkD7SHaXGoIR5jLWVjf0JEzv6J04A61.png" alt="Waste Connection Logo" class="logo">

<div class="calendar">
    <div class="calendar-title">AUGUST 2024</div>
    <table>
        <thead>
            <tr>
                <th>Sunday</th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
                <th>Saturday</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td onclick="showModal(1)"><span class="day-number">1</span></td>
                <td onclick="showModal(2)"><span class="day-number">2</span></td>
                <td onclick="showModal(3)"><span class="day-number">3</span></td>
            </tr>
            <tr>
                <td onclick="showModal(4)"><span class="day-number">4</span></td>
                <td onclick="showModal(5)"><span class="day-number">5</span></td>
                <td onclick="showModal(6)"><span class="day-number">6</span></td>
                <td onclick="showModal(7)"><span class="day-number">7</span></td>
                <td onclick="showModal(8)"><span class="day-number">8</span></td>
                <td onclick="showModal(9)"><span class="day-number">9</span></td>
                <td onclick="showModal(10)"><span class="day-number">10</span></td>
            </tr>
            <tr>
                <td onclick="showModal(11)"><span class="day-number">11</span></td>
                <td onclick="showModal(12)"><span class="day-number">12</span></td>
                <td onclick="showModal(13)"><span class="day-number">13</span></td>
                <td onclick="showModal(14)"><span class="day-number">14</span></td>
                <td onclick="showModal(15)"><span class="day-number">15</span></td>
                <td onclick="showModal(16)"><span class="day-number">16</span></td>
                <td onclick="showModal(17)"><span class="day-number">17</span></td>
            </tr>
            <tr>
                <td onclick="showModal(18)"><span class="day-number">18</span></td>
                <td onclick="showModal(19)"><span class="day-number">19</span></td>
                <td onclick="showModal(20)"><span class="day-number">20</span></td>
                <td onclick="showModal(21)"><span class="day-number">21</span></td>
                <td onclick="showModal(22)"><span class="day-number">22</span></td>
                <td onclick="showModal(23)"><span class="day-number">23</span></td>
                <td onclick="showModal(24)"><span class="day-number">24</span></td>
            </tr>
            <tr>
                <td onclick="showModal(25)"><span class="day-number">25</span></td>
                <td onclick="showModal(26)"><span class="day-number">26</span></td>
                <td onclick="showModal(27)"><span class="day-number">27</span></td>
                <td onclick="showModal(28)"><span class="day-number">28</span></td>
                <td onclick="showModal(29)"><span class="day-number">29</span></td>
                <td onclick="showModal(30)"><span class="day-number">30</span></td>
                <td onclick="showModal(31)"><span class="day-number">31</span></td>
            </tr>
        </tbody>
    </table>
</div>

<!-- The Modal -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p id="modalText">Daily Objectives:</p>
        <textarea id="modalTextarea" class="modal-textarea"></textarea>
        <button class="save-btn" onclick="saveChanges()">Save</button>
    </div>
</div>

<script>
    var modal = document.getElementById("myModal");
    var span = document.getElementsByClassName("close")[0];
    var modalTextarea = document.getElementById("modalTextarea");
    var currentDay = null;

    function showModal(day) {
        currentDay = day;
        var savedText = localStorage.getItem("day" + day) || "";
        modalTextarea.value = savedText;
        modal.style.display = "block";
    }

    function saveChanges() {
        if (currentDay !== null) {
            localStorage.setItem("day" + currentDay, modalTextarea.value);
            alert("Changes saved!");
            modal.style.display = "none";
        }
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

</body>
</html>
